version: 0.1

phases:
  pre_build:
    commands:
      - REPOSITORY_URI=268021257063.dkr.ecr.us-east-1.amazonaws.com/test/vertx-repo
      - IMAGE_TAG=latestbuild
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Build started on `date`
      - echo building the Docker image
      - docker build -t 268021257063.dkr.ecr.us-east-1.amazonaws.com/test/vertx-repo:latest .
      - docker tag 268021257063.dkr.ecr.us-east-1.amazonaws.com/test/vertx-repo:latest 268021257063.dkr.ecr.us-east-1.amazonaws.com/test/vertx-repo:latest-build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing the Docker image
      - docker push 268021257063.dkr.ecr.us-east-1.amazonaws.com/test/vertx-repo:latest
      - docker push 268021257063.dkr.ecr.us-east-1.amazonaws.com/test/vertx-repo:latest-build
artifacts:
  files:
    - target/hello-verticle-3.9.0.jar.jar
